# Generated by Django 5.2.8 on 2025-11-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_exams_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
