# Generated by Django 5.2.8 on 2025-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_authorized_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default='000000000000', max_length=12, unique=True),
        ),
    ]
