# Generated by Django 5.2.8 on 2025-11-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_exams_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbanks',
            name='questionbank_name',
            field=models.CharField(default='General Question Bank', max_length=200),
        ),
    ]
