# Generated by Django 5.2.8 on 2025-11-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_number',
            new_name='LRN_number',
        ),
    ]
