# Generated by Django 5.2.8 on 2025-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_questionbanks_questionbank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbanks',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='questionbanks',
            name='question_text',
        ),
        migrations.AddField(
            model_name='questionbanks',
            name='question_and_answer',
            field=models.JSONField(default=list),
        ),
    ]
