# Generated by Django 5.2.8 on 2025-11-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_questionbanks_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbanks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
