# Generated by Django 5.2.8 on 2025-11-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profiles',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='Student Profiles',
        ),
    ]
