# Generated by Django 5.2.8 on 2025-12-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_questionbanks_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='camera_calibration_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
