# Generated by Django 5.2.8 on 2025-12-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studentprofile_camera_calibration_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveExamSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentprofile')),
            ],
            options={
                'verbose_name': 'Active Exam Session',
                'verbose_name_plural': 'Active Exam Sessions',
                'db_table': 'Active Exam Sessions',
            },
        ),
    ]
